version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-noarg
    versions:
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.30
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - 1.4.30
  - dependency-name: org.webjars:bootstrap
    versions:
    - 4.6.0
